# Platform page copy. Every value is (Bahasa Indonesia, English). Sources: PRD §5.2, §9 (NFR-1..9), §11 and the
# architecture diagram; DECISIONS D2, D7, D13. Describes the platform's design; the model provider is deliberately
# not named (D13). The Indonesian side still needs the native-speaker review that gates release.

PLATFORM = {
    "meta_title": ("Platform | obscur4", "Platform | obscur4"),
    "hero_h": ("Platform di balik setiap ==pekerjaan==.", "The platform behind every ==engagement==."),
    "hero_sub": ("Satu sistem terkelola dirancang untuk menjalankan semua layanan, dari permintaan sampai laporan. Inilah susunannya dan letak batas-batasnya.",
                 "One governed system is designed to run every service, from request to report. This is how it fits together and where the boundaries sit."),

    "stack_h": ("Tujuh lapisan, satu arah perjalanan", "Seven layers, one direction of travel"),
    "stack_intro": ("Setiap permintaan turun melewati tujuh lapisan yang sama. Tidak ada yang mencapai lingkungan uji tanpa melewati lapisan otorisasi lebih dulu.",
                    "A request moves down through the same seven layers every time. Nothing reaches a test environment without passing the authorization layer first."),
    "layers": [
        (("Antarmuka pekerjaan", "Engagement interface"),
         ("Permintaan masuk lewat konsol web, baris perintah, atau chat. Tidak ada yang berjalan langsung dari sini.",
          "Requests arrive through a web console, the command line or chat. Nothing runs from here directly.")),
        (("Kendali otorisasi dan ruang lingkup", "Authorization and scope control"),
         ("Setiap tindakan diperiksa terhadap otorisasi tertulis: ruang lingkup, batas waktu, dan daftar sasaran yang diizinkan. Permintaan di luar lingkup ditolak beserta alasannya.",
          "Every action is checked against a written authorization: scope, time-box and target allowlist. Out-of-scope requests are refused with a reason.")),
        (("Inti orkestrasi", "Orchestration core"),
         ("Perencana memecah pekerjaan menjadi langkah, memilih jalur model dan alat untuk tiap langkah, dan mencatat setiap eksekusi di buku besar.",
          "A planner breaks the work into steps, picks the model lane and tool for each, and records every run in a ledger.")),
        (("Harness eksekusi", "Execution harnesses"),
         ("Pekerja terisolasi menjalankan langkah-langkahnya: menulis probe, menjalankan perintah, dan memanggil alat, masing-masing dengan kredensialnya sendiri.",
          "Isolated workers carry out the steps: they write probes, run commands and call tools, each with its own credentials.")),
        (("Perangkat penilaian", "Assessment tooling"),
         ("Analisis statis dan runtime aplikasi mobile, pemindaian kode dan dependensi, pengujian web, dan pengintaian pasif.",
          "Mobile static and runtime analysis, code and dependency scanning, web testing and passive reconnaissance.")),
        (("Lingkungan uji terisolasi", "Isolated test environments"),
         ("Lingkungan sekali pakai dan tersegmentasi jaringan: kontainer sementara, kumpulan perangkat emulasi, lab loopback, dan staging yang diotorisasi klien.",
          "Disposable, network-segmented environments: ephemeral containers, an emulated device farm, loopback labs and client-authorized staging.")),
        (("Bukti, analisis, dan pelaporan", "Evidence, analysis and reporting"),
         ("Artefak mentah disimpan dengan hash, temuan ditulis dari artefak itu, dan laporan disanitasi saat diekspor.",
          "Raw artifacts are stored with hashes, findings are written from them, and reports are sanitized on export.")),
    ],
    "feedback": ("Pelajaran dari setiap pekerjaan kembali ke lapisan pengetahuan, sehingga pekerjaan berikutnya dimulai dari yang terakhir.",
                 "Lessons from each engagement return to the knowledge layer, so the next one starts from the last."),

    "lanes_h": ("Jalur model", "Model lanes"),
    "lanes_intro": ("Pekerjaan diarahkan menurut tingkat kesulitan, sehingga kedalaman hanya dibayar di tempat yang membutuhkannya.",
                    "Work is routed by difficulty, so depth is paid for only where it is needed."),
    "lanes": [
        (("Frontier", "Frontier"), ("Penalaran dan penilaian yang sulit.", "Hard reasoning and judgment."),
         [("Mengurai tabel rekaman yang diobfuskasi", "Decode an obfuscated record table"),
          ("Merancang perbandingan terkontrol", "Plan a controlled comparison"),
          ("Meninjau temuan sebelum dikirim", "Review a finding before it ships")]),
        (("Hemat biaya", "Cost-efficient"), ("Langkah rutin yang terdefinisi jelas.", "Routine, well-defined steps."),
         [("Mengambil data dari log peluncuran", "Extract fields from launch logs"),
          ("Menyusun laporan", "Assemble the report"),
          ("Memeriksa eksekusi terhadap runbook", "Check a run against its runbook")]),
        (("Self-hosted", "Self-hosted"), ("Pekerjaan yang tidak boleh keluar dari lingkungan kami.", "Work that should not leave our environment."),
         [("Memproses artefak klien yang harus tetap bersama kami", "Process client artifacts that must stay with us")]),
    ],

    "provider_h": ("Dibangun di atas platform model enterprise", "Built on an enterprise model platform"),
    "provider_intro": ("Akses model dirancang di sekitar platform dan konsol enterprise milik penyedia model frontier terkemuka, dipakai sebagai infrastruktur, bukan sebagai produk.",
                       "Model access is designed around a leading frontier-model provider's enterprise platform and console, used as infrastructure rather than as the product."),
    "provider": [
        (("Workspace per jalur", "Workspaces per lane"),
         ("Setiap jalur model berjalan di workspace-nya sendiri, sehingga jalur tidak pernah berbagi kunci, batas, atau log.",
          "Each model lane runs in its own workspace, so lanes never share keys, limits or logs.")),
        (("Kunci dengan cakupan terbatas", "Scoped keys"),
         ("Kunci diterbitkan per workspace dan per pekerja, lalu dirotasi. Kunci tidak pernah muncul di laporan atau log.",
          "Keys are issued per workspace and per worker, and rotated. They never appear in reports or logs.")),
        (("Batas biaya", "Spend limits"),
         ("Setiap pekerjaan punya plafon biaya yang ditegakkan di tingkat workspace.",
          "Every engagement has a cost ceiling, enforced at the workspace level.")),
        (("Log penggunaan", "Usage logs"),
         ("Panggilan model dicatat dan dikaitkan ke buku besar eksekusi, sehingga setiap langkah dapat ditelusuri.",
          "Model calls are logged and tied back to the run ledger, so every step can be traced.")),
        (("Tidak dilatih dengan data kami", "No training on our data"),
         ("Kami memilih penyedia yang ketentuan komersialnya mengecualikan masukan dan keluaran kami dari pelatihan model.",
          "We choose providers whose commercial terms exclude our inputs and outputs from model training.")),
        (("Tidak bergantung pada penyedia", "Provider-independent"),
         ("Inti orkestrasi menyapa jalur, bukan vendor. Penyedia sebuah jalur dapat diganti tanpa menyentuh lapisan di atasnya.",
          "The orchestration core addresses lanes, not vendors. A lane can change provider without touching the layers above it.")),
    ],

    "controls_h": ("Kendali di setiap lapisan", "Controls at every layer"),
    "controls": [
        (("Isolasi identitas dan rahasia", "Identity and secret isolation"),
         ("Kredensial per jalur dan per klien; tidak ada jalur dari satu klien ke klien lain.",
          "Per-lane and per-client credentials; no path from one client to another.")),
        (("Kendali batas data", "Data-boundary control"),
         ("Artefak klien tetap di workspace-nya; ekspor melewati tahap penyamaran.",
          "Client artifacts stay in their workspace; exports pass a redaction step.")),
        (("Keterlacakan", "Auditability"),
         ("Setiap tindakan dapat ditelusuri ke pelaku dan rujukan otorisasi, dan dapat direproduksi.",
          "Every action is attributable to an actor and an authorization reference, and reproducible.")),
        (("Default yang aman", "Safe defaults"),
         ("Pasif dan baca-saja lebih dulu; apa pun yang intrusif memerlukan otorisasi tercatat dan dibatasi waktu.",
          "Passive and read-only first; anything intrusive needs recorded authorization and is time-boxed.")),
    ],

    "boundary_h": ("Yang dilihat klien, dan yang tetap internal", "What clients see, and what stays internal"),
    "boundary_client": (("Klien melihat", "Clients see"),
                        [("Permintaan dan ruang lingkup", "Intake and scope"), ("Catatan otorisasi", "Authorization records"),
                         ("Laporan dan ekspor bukti", "Reports and evidence export")]),
    "boundary_internal": (("Tetap internal", "Stays internal"),
                          [("Orkestrasi dan jalur model", "Orchestration and model lanes"), ("Harness eksekusi", "Execution harnesses"),
                           ("Runbook dan lapisan pengetahuan", "Runbooks and the knowledge layer")]),

    "band_h": ("Ingin melihat platform lebih rinci?", "Want to see the platform in detail?"),
    "band_cta": ("Minta sesi briefing teknis", "Request a technical briefing"),
}
